create a new book list
wolox-training/fr-angularjs pull request #2
Opened 2021-02-23 14:00 UTC by FlorRodriguezA

## Summary
- Used flexbox for all  book covers, and inside the book cover too 

## Screenshot
![Captura de pantalla de 2021-02-23 10-59-21](https://user-images.githubusercontent.com/49420114/108854133-4403b480-75c6-11eb-9f47-ec2d949a9c35.png)

## Trello Card
https://trello.com/c/3KkyuGEw

2021-02-23 19:24 UTC, FlorRodriguezA commented
Summary
Reduced the margin, add a nav bar in the top, and a the Logo Wolox

Screenshot
images.githubusercontent.com/49420114/108895880-e9348200-75f2-11eb-8b37-6524695c126e.png)

Trello Card
https://trello.com/c/HUcyRij8

2021-02-23 19:44 UTC, FlorRodriguezA commented
Summary
I added the sticky position for the bar

Screenshot
![Captura de pantalla de 2021-02-23 16-44-19](https://user-images.githubusercontent.com/49420114/108898804-6ca3a280-75f6-11eb-8330-16bfbb5ea669.png)


Trello Card
https://trello.com/c/HUcyRij8

2021-02-24 16:25 UTC, mcallegari10 requested changes
I dont see the detail view you were working on the main branch. Remember to do a `git pull` and then move to this branch and `git merge main`. That way you'll bring all your work into this one 😄

2021-02-24 16:25 UTC, mcallegari10 commented on listado-de-libros/scss/detail.scss
> +.all-group {
I think there's a better name for this class

2021-02-24 16:25 UTC, mcallegari10 commented on listado-de-libros/scss/detail.scss
> +.all-group2 {
Same for this, avoid using numbers in class names 😝

2021-02-24 16:25 UTC, mcallegari10 commented on listado-de-libros/scss/detail.scss
> +.group {
Group of what?

2021-02-24 16:25 UTC, mcallegari10 commented on listado-de-libros/scss/detail.scss
> +  margin-right: 36px;
Always use the `margin` property instead of specifying in multiple margin properties. For example, this can be:

`margin: 35px 35px 0 0;`

2021-02-24 16:25 UTC, mcallegari10 commented on listado-de-libros/scss/detail.scss
> +}
Remember to add the EOF 😄

2021-02-24 16:25 UTC, mcallegari10 commented on listado-de-libros/scss/detail.scss
> +  margin-right: 30px;
Same here for the margins

2021-02-24 16:25 UTC, mcallegari10 commented on listado-de-libros/scss/detail.scss
> +  margin-right: 30px;
Same here

2021-02-24 16:25 UTC, mcallegari10 commented on listado-de-libros/scss/detail.scss
> +  width: 1169px;
If you set this fixed size, the navbar will not properly adapt itself to other display sizes. What you can do is set it to:

`width: 100vw;` or `width: 100%;`

With the first one, you are setting it to be the width of the ViewWidth of the browser window. The second is telling the navbar to occupy the available space it has according to its parent

2021-02-24 16:25 UTC, mcallegari10 commented on listado-de-libros/scss/detail.scss
> +}
Move this to the `application.scss` since that's your main file 😄

2021-02-24 16:25 UTC, mcallegari10 commented on listado-de-libros/index.html
> +      <div class="nav-bar">
This should be a `nav` tag, not a `div`

2021-02-24 16:25 UTC, mcallegari10 commented on listado-de-libros/index.html
> +      <div class="nav-bar">
And maybe this should be outside the main `div`

2021-02-24 19:35 UTC, FlorRodriguezA commented
Summary
Made all the requested changes. Add a blue bar on the top and a logout. Also changed flex styles for the covers
I forgot to delete line 10 in the html (class blue-nav-bar)

Screenshot
![Captura de pantalla de 2021-02-24 16-28-06](https://user-images.githubusercontent.com/49420114/109055679-40ebef80-76be-11eb-8b51-c49a76c71645.png)


Trello Card
https://trello.com/c/HUcyRij8

2021-02-24 20:54 UTC, mcallegari10 requested changes

2021-02-24 20:54 UTC, mcallegari10 commented on listado-de-libros/index.html
> +    <nav class="blue-nav-bar"></nav>
What's this `blue-nav-bar` for? 🤔

2021-02-24 20:54 UTC, mcallegari10 commented on listado-de-libros/index.html
> +          <a class="logout">Logoout</a>
```suggestion
          <a class="logout">Log out</a>
```

2021-02-24 20:54 UTC, mcallegari10 commented on listado-de-libros/scss/detail.scss
>  }
Move this to the `application.scss` too 😉

2021-02-24 20:54 UTC, mcallegari10 commented on listado-de-libros/scss/detail.scss
> +  margin: 26px 0 0 600px;
`600px` whaaaaaaat 💥 . Remember not to position elements with margin 😄

2021-02-24 20:54 UTC, mcallegari10 commented on listado-de-libros/index.html
> +          <a class="logout">Logoout</a>
BTW, I think this is not part of the `navbar`

2021-02-24 20:54 UTC, mcallegari10 commented on listado-de-libros/scss/detail.scss
> +  position: absolute;
I think this should not be `absolute` 🤔

2021-02-24 20:54 UTC, mcallegari10 commented on listado-de-libros/scss/detail.scss
> +  width: 100%;
The proper way to set a width is:

```css
.my-class {
  ...
  max-width: <pixels>px;
  width: 100%;
  ...
}
```

2021-02-25 12:01 UTC, FlorRodriguezA commented
Summary
Used Flex to modify the position of the elements of the nav bar. 
Used top and right to position them correctly, with relative position

Screenshot
![Captura de pantalla de 2021-02-25 09-00-41](https://user-images.githubusercontent.com/49420114/109150724-06c73000-7748-11eb-845c-ffe3e9de2ca8.png)

Trello Card
https://trello.com/c/HUcyRij8

2021-02-25 15:00 UTC, mcallegari10 requested changes

2021-02-25 15:00 UTC, mcallegari10 commented on listado-de-libros/scss/detail.scss
> +.nav-bar {
I think the `nav` classes can be moved to their own file 😄 . And BTW, this is the `detail` or `book-list` SASS file?

2021-02-25 15:00 UTC, mcallegari10 commented on listado-de-libros/scss/detail.scss
> +  top: 20px;
If the position is `relative`, you won't need this anymore

2021-02-25 15:00 UTC, mcallegari10 commented on listado-de-libros/scss/detail.scss
> +  max-width: 1300px;
I think this max is not necessary 🤔

2021-02-25 15:00 UTC, mcallegari10 commented on listado-de-libros/scss/detail.scss
> +  right: 50px;
I think this should be a `nav-bar` padding

2021-02-25 18:47 UTC, FlorRodriguezA commented
Summary
Create a new Scss (nav-bar.scss). And I fixed the errors.
And I changed the title


Screenshot
![Captura de pantalla de 2021-02-25 15-45-48](https://user-images.githubusercontent.com/49420114/109201503-ae605480-7780-11eb-8f0d-dcfe105102ad.png)


Trello Card
https://trello.com/c/HUcyRij8

2021-02-25 22:10 UTC, mcallegari10 commented on listado-de-libros/scss/nav-bar.scss
> +}
Remember the EOF line 😄

2021-02-25 22:11 UTC, mcallegari10 approved these changes
Remember to center the list and ready to go 🚀

2021-02-26 18:59 UTC, mcallegari10 approved these changes
![](https://media.giphy.com/media/l1KsJua7qIQnevGyk/giphy.gif)

2021-02-26 19:07 UTC, merged