Login
wolox-training/fr-angularjs pull request #4
Opened 2021-02-27 14:11 UTC by FlorRodriguezA

## Summary
-I finished the login card

## Screenshot
![Captura de pantalla de 2021-02-27 11-10-42](https://user-images.githubusercontent.com/49420114/109389746-79711080-78ec-11eb-965c-61fcb6e3919b.png)

## Trello Card
https://trello.com/c/N1ak4TXY

2021-03-01 21:51 UTC, mcallegari10 requested changes

2021-03-01 21:51 UTC, mcallegari10 commented on login/index.html
> +        <label for="email">Email</label><br>
We don't usually use `br` tags. If you need space, use `margin` 😄

2021-03-01 21:51 UTC, mcallegari10 commented on login/scss/detail.scss
> +body {
Don't style the `body` directly. If you need a new container, create a wrapper `div`

2021-03-01 21:51 UTC, mcallegari10 commented on login/index.html
> +        <a href="../listado-de-libros/index.html">
Remember the identation

2021-03-01 21:51 UTC, mcallegari10 commented on login/index.html
> +          <input class="login" type="button"  value="Log In">
For submit buttons, we use the `button` element with a `submit` type

2021-03-01 21:51 UTC, mcallegari10 commented on login/index.html
> +          <input class="singup" type="submit" value="Sing Up">
I think this is actually a link, what do you think?

2021-03-01 21:51 UTC, mcallegari10 commented on login/scss/detail.scss
> +  background-color: $wild-sand;
Remember the wrapper container trick we saw the other day, try to use that 😄

2021-03-01 21:51 UTC, mcallegari10 commented on login/scss/detail.scss
> +  position: relative;
I think this is not needed

2021-03-01 21:51 UTC, mcallegari10 commented on login/scss/detail.scss
> +label {
Don't style HTML tags directly, create a class for this

2021-03-01 21:51 UTC, mcallegari10 commented on login/scss/detail.scss
> +  position: relative;
No need for this

2021-03-01 21:51 UTC, mcallegari10 commented on login/scss/detail.scss
> +.data {
I think this is not a good name 🤔 . Maybe something like `input`?

2021-03-01 21:51 UTC, mcallegari10 commented on login/scss/detail.scss
> +  position: relative;
Not needed

2021-03-01 21:51 UTC, mcallegari10 commented on login/scss/detail.scss
> +.border {
Why a new `div` for this? I think you can achieve the same with just the original element 😄

2021-03-01 21:51 UTC, mcallegari10 commented on login/scss/detail.scss
> +  margin-top: 15px;
Remember to use the shorthand

2021-03-01 21:51 UTC, mcallegari10 commented on login/scss/equalizer.scss
> +$equalizer-black: #000;
Why a new equalizer?

2021-03-02 18:05 UTC, FlorRodriguezA commented
Summary
-I finished the login card

Screenshot
![Captura de pantalla de 2021-03-02 15-03-42](https://user-images.githubusercontent.com/49420114/109693626-a598c580-7b68-11eb-8845-b9059df53328.png)

Trello Card
https://trello.com/c/N1ak4TXY

2021-03-02 19:21 UTC, mcallegari10 approved these changes
Check those comments and ready to merge 🚀 . Great job!

2021-03-02 19:21 UTC, mcallegari10 commented on login/index.html
> +          <button class="login" type="submit" formaction="../listado-de-libros/index.html" value="Log In">Log In</button>
The `formaction` is not needed 😄

2021-03-02 19:21 UTC, mcallegari10 commented on login/scss/detail.scss
> +label {
Ping here

2021-03-02 19:21 UTC, mcallegari10 commented on login/scss/detail.scss
> +  position: relative;
Ping here

2021-03-03 11:33 UTC, merged