Responsive
wolox-training/fr-angularjs pull request #5
Opened 2021-03-02 22:44 UTC by FlorRodriguezA

## Summary
- Responsive card

## Screenshot
![Captura de pantalla de 2021-03-02 19-43-36](https://user-images.githubusercontent.com/49420114/109725301-b27cdf80-7b8f-11eb-9780-4f0c5c9896d9.png)
![Captura de pantalla de 2021-03-02 19-44-02](https://user-images.githubusercontent.com/49420114/109725306-b446a300-7b8f-11eb-87a7-2dd9c6a2f36e.png)

## Trello Card
https://trello.com/c/M0QUonOW

2021-03-03 14:30 UTC, mcallegari10 requested changes
I think you are missing the meta tag in the index.html. Check this https://css-tricks.com/snippets/html/responsive-meta-tag/

2021-03-03 14:30 UTC, mcallegari10 commented on maquetado/index.html
> +   </div>
I think this isn't necessary

2021-03-03 14:30 UTC, mcallegari10 commented on maquetado/scss/detail.scss
> +  [class='cover'] {
Use the class notation 😝 

```css
.cover {
  ...
}
```

2021-03-03 14:30 UTC, mcallegari10 commented on maquetado/scss/detail.scss
> +    width: 100vw;
I think this isn't necessary

2021-03-03 14:30 UTC, mcallegari10 commented on maquetado/scss/detail.scss
> +  }
Maybe you can use `nth-child` so you won't need to repeat so much 😄

2021-03-03 14:30 UTC, mcallegari10 commented on maquetado/scss/detail.scss
> +}
EOF line

2021-03-03 14:30 UTC, mcallegari10 commented on maquetado/scss/detail.scss
> +    width: 100%;
This is already in the class, no need to add 😄

2021-03-03 14:30 UTC, mcallegari10 commented on maquetado/scss/detail.scss
> +    display: flex;
This is already in the class

2021-03-03 14:30 UTC, mcallegari10 commented on maquetado/scss/detail.scss
> +    flex-flow: column-reverse;
`reverse` is what you need? 🤔

2021-03-03 14:30 UTC, mcallegari10 commented on maquetado/scss/detail.scss
> +      bottom: 200px;
It's OK. Maybe you can use percentages or variables for the book sizes

2021-03-03 14:30 UTC, mcallegari10 commented on maquetado/scss/detail.scss
> +$widthBadgeCellphone: calc(var($widthBadgeDesktop) * 70%);
I think this won't work. The proper way to use SASS variables in `calc` functions is:

```scss
$widthBadgeCellphone: calc(#{$widthBadgeDesktop} * 70%);
```

Also, available for other CSS functions if you need to use SASS variables 😉

2021-03-03 14:30 UTC, mcallegari10 commented on maquetado/scss/detail.scss
> +  height: 768px;
I think this shouldn't be here or this size 🤔

2021-03-03 17:52 UTC, FlorRodriguezA commented
Summary
I finished the Responsive card

Screenshot
![Captura de pantalla de 2021-03-03 14-51-47](https://user-images.githubusercontent.com/49420114/109849317-02ab7e80-7c30-11eb-8ac5-60d3b4a9cba1.png)

Trello Card
https://trello.com/c/M0QUonOW

2021-03-04 16:42 UTC, mcallegari10 approved these changes
Just those 2 details 😄 . Great job!

2021-03-04 16:42 UTC, mcallegari10 commented on maquetado/scss/detail.scss
> +  }
Delete this 😄

2021-03-04 16:42 UTC, mcallegari10 commented on maquetado/scss/detail.scss
> +    &::after {
```suggestion
  .cover-container::after {
```

2021-03-05 14:32 UTC, FlorRodriguezA commented
Summary
I finished the css grid card

Screenshot
![Captura de pantalla de 2021-03-05 11-29-32](https://user-images.githubusercontent.com/49420114/110129136-5d66e680-7da6-11eb-8e54-8bcee69bf1e9.png)
![Captura de pantalla de 2021-03-05 11-29-44](https://user-images.githubusercontent.com/49420114/110129140-5e981380-7da6-11eb-9d31-999398a5c884.png)
![Captura de pantalla de 2021-03-05 11-29-54](https://user-images.githubusercontent.com/49420114/110129141-5f30aa00-7da6-11eb-9a27-a6a6924ec347.png)


Trello Card
https://trello.com/c/3ePt3n4T

2021-03-08 20:04 UTC, mcallegari10 requested changes

2021-03-08 20:04 UTC, mcallegari10 commented on maquetado/scss/detail.scss
> +
```suggestion
```

2021-03-08 20:04 UTC, mcallegari10 commented on maquetado/scss/detail.scss
> +  display: grid;
Remember to delete the `display: flex;` above

2021-03-08 20:04 UTC, mcallegari10 commented on maquetado/scss/detail.scss
> +    display: grid;
No need for this 😄

2021-03-08 20:04 UTC, mcallegari10 commented on maquetado/scss/detail.scss
> +    height: 768px;
You can leave it in `auto` I think

2021-03-08 20:04 UTC, mcallegari10 commented on maquetado/scss/detail.scss
> +@media only screen and (max-width: 1366px) {
Remember to move the breakpoint to a variable 😄

2021-03-08 20:04 UTC, mcallegari10 commented on maquetado/scss/detail.scss
> +    align-self: flex-start;
I think this is not necessary or check that flex, remember this is grid 😝

2021-03-08 20:04 UTC, mcallegari10 commented on maquetado/scss/detail.scss
> +@media only screen and (max-width: 1024px) {
Move breakpoint to a variable 😄

2021-03-08 20:04 UTC, mcallegari10 commented on maquetado/scss/detail.scss
> +    height: 570px;
No need for the height

2021-03-11 14:43 UTC, mcallegari10 approved these changes

2021-03-11 14:46 UTC, mcallegari10 commented
![](https://media.giphy.com/media/S6qkS0ETvel6EZat45/giphy.gif)

2021-03-12 16:25 UTC, merged